CREATE TABLE PLANT_CAT (
catID INT(2) UNSIGNED ZEROFILL DEFAULT 00 PRIMARY KEY,
plantCategory VARCHAR(30) DEFAULT '' NOT NULL
);

CREATE TABLE PLANT_CODES (
codeID INT(2) UNSIGNED ZEROFILL DEFAULT 00 AUTO_INCREMENT PRIMARY KEY,
codeNum INT(8) DEFAULT 0 NOT NULL,
codeURL VARCHAR(40) DEFAULT '' NOT NULL
);

CREATE TABLE PLANT_GEN (
genusID INT(3) UNSIGNED ZEROFILL DEFAULT 000 AUTO_INCREMENT PRIMARY KEY,
plantGenus VARCHAR(50) DEFAULT '' NOT NULL,
commonName VARCHAR(30),
genDesc TEXT,
codeID INT(2) DEFAULT 00,
zoneID INT(2) UNSIGNED ZEROFILL DEFAULT 00,
catID INT(2) UNSIGNED ZEROFILL DEFAULT 00 NOT NULL
);

CREATE TABLE PLANT_PLANTS (
genusID INT(3) UNSIGNED ZEROFILL DEFAULT 000 NOT NULL,
isNew VARCHAR(5),
codeID INT(2),
varietalName VARCHAR(50) DEFAULT '',
description TEXT,
hrURL VARCHAR(60),
lrURL VARCHAR(60),
potID INT(2) UNSIGNED ZEROFILL DEFAULT 00 NOT NULL,
priceID INT(2) UNSIGNED ZEROFILL DEFAULT 00 NOT NULL,
plantID INT(4) UNSIGNED ZEROFILL DEFAULT 0000 AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE PLANT_POTS (
potID INT(2) UNSIGNED ZEROFILL DEFAULT 00 AUTO_INCREMENT PRIMARY KEY,
potSize VARCHAR(20) DEFAULT '' NOT NULL
);

CREATE TABLE PLANT_PRICE (
priceID INT(2) UNSIGNED ZEROFILL DEFAULT 00 AUTO_INCREMENT PRIMARY KEY,
price VARCHAR(15) DEFAULT '' NOT NULL
);

CREATE TABLE PLANT_ZONE (
zoneID INT(2) UNSIGNED ZEROFILL DEFAULT 00 AUTO_INCREMENT PRIMARY KEY,
zone VARCHAR(15) DEFAULT '' NOT NULL
);

CREATE TABLE SS_CAT (
catID INT(1) UNSIGNED ZEROFILL DEFAULT 0 AUTO_INCREMENT PRIMARY KEY,
SSCat VARCHAR(10) DEFAULT '' NOT NULL,
pSize CHAR(2) NOT NULL
);

CREATE TABLE SS_GEN (
genID INT(3) UNSIGNED ZEROFILL DEFAULT 000 AUTO_INCREMENT PRIMARY KEY,
category INT(1) DEFAULT 0 NOT NULL,
plantGenus VARCHAR(15) DEFAULT '' NOT NULL
);

CREATE TABLE SS_PLANT (
plant_ID INT(3) UNSIGNED ZEROFILL DEFAULT 000 AUTO_INCREMENT PRIMARY KEY,
genus_ID INT(3) UNSIGNED ZEROFILL DEFAULT 000 NOT NULL,
varietal VARCHAR(30),
description TEXT,
hrURL VARCHAR(60),
lrURL VARCHAR(60),
price_code INT(1) DEFAULT 4 NOT NULL
);

CREATE TABLE SS_PRICE (
priceID INT(1) AUTO_INCREMENT PRIMARY KEY,
price VARCHAR(10) DEFAULT '' NOT NULL
);